import os
import sys
import subprocess
import re
import numpy as np
import pandas as pd
import pysam
import anndata as ad

#################################### USER CONFIGURATION ####################################

# Path to config file
configfile: 'config/config_v2.yaml'

# Create the output directory
outdir = config['outdir']
if not os.path.exists(outdir):
    os.makedirs(outdir)

# Path to barcode table
barcode_file = f"{outdir}/barcodes.tsv"

#################################### PREP BARCODES AND SAMPLETABLE ####################################

# NOTE: 
# - Manually prep data frames for metadata and sampletable
# - Ensure that the meta_df includes the three required columns
#   specified in config['key_col'], config['index_col'], and config['bam_col']

# Prep sampletable
sampletable = pd.read_csv(config['sampletable']).set_index(config['index_col'], drop=False)
sampletable[config['bam_col']] = config['bam_dir'] + "/" + sampletable.index + '_possorted_genome_bam.bam'

# Add a column for seq read length, if missing
if 'read_length' not in list(sampletable.columns): 
    rl = []
    for bamfile in list(sampletable[bam_col]):
        cmd = f"samtools view {bamfile} | cut -f 10 | head -n 1 | wc -m"
        read_length = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        rl.append(read_length.stdout.strip())
    sampletable['read_length'] = rl
    sampletable.to_csv(config['sampletable'], index=False)

# Break if input bams don't align with sampletable
missing_bams = [b for b in sampletable[config['bam_col']] if not os.path.isfile(b)]
if len(missing_bams) > 0:
    raise ValueError(f"{missing_bams} not found in the directory!")

# Prep barcode table
meta_list = []
for celltype, path in config['adata'].items():
    # Read AnnData
    meta_df = ad.read_h5ad(path).obs[list(config['all_cols'])]
    # Add new columns for celltypes and barcodes
    meta_df['celltype'] = celltype
    meta_df['barcode'] = meta_df.index
    # Remove sample suffixes from the barcodes
    barcode_df = meta_df['barcode'].str.split('_', expand=True)
    barcode_df.columns = ['barcode', config['index_col']]
    # Add new columns to the metadata
    meta_df['barcode'] = barcode_df['barcode']
    meta_df[config['index_col']] = barcode_df[config['index_col']]
    meta_df[config['key_col']] = meta_df[config['disease_col']].astype(str) + "-" + meta_df['celltype'].astype(str)
    meta_list.append(meta_df)

# Save all barcodes in a tsv file
meta_df = pd.concat(meta_list, axis=0)

# Add bam file paths to the metadata table and save as a tsv file
meta_df = pd.merge(sampletable.loc[:, [config['index_col'], config['key_col'], config['bam_col']]].reset_index(drop=True),
                   meta_df,
                   how="right",
                   on=[config['index_col']])
# meta_df.to_csv(barcode_file, sep="\t", index=False)

print(meta_df)
